# Site
name: "Totoro"
title: "Totoro"
description: "We are pengies and we like exploring."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: friedsoda1992@gmail.com

# Authors
authors:
  mantie:
    name: Mantie
    display_name: Mantie
    avatar: 'assets/images/avatar.png'
    description: "The 1st cutest penguin in this world."
  romie:
    name: Romie
    display_name: Romie
    avatar: 'assets/images/avatar.png'
    description: "Cute and kind and smart nechan."
  pinbi:
    name: Pinbi
    display_name: Pinbi
    avatar: 'assets/images/avatar.png'
    description: "I'm the leader in this house. Ahahahahah. And I'm not a plushie..."
  vicek:
    name: Víček
    display_name: Víček
    avatar: 'assets/images/avatar.png'
    description: "I saw everything. I mean about Romie."
  chika:
    name: Chika
    display_name: Chika   
    avatar: 'assets/images/avatar.png'
    description: "Metal is the best."
  pinpin:
    name: Pinpin
    display_name: Pinpin   
    avatar: 'assets/images/avatar.png'
    description: "Oresama is the king!!"
  snutie:
    name: Snutie
    display_name: Snutie
    avatar: 'assets/images/avatar.png'
    description: "Sister of だれ."
  genis:
    name: Small Geni
    display_name: Small Geni
    avatar: 'assets/images/avatar.png'
    description: "Genigeni, genigeni geni."
  genil:
    name: Big Geni
    display_name: Big Geni
    avatar: 'assets/images/avatar.png'
    description: "Geni, genigenigeni genigeni."
  kadlik:
    name: Kadlik
    display_name: Kadlik
    avatar: 'assets/images/avatar.png'
    description: "Time for lunch.. (going out)"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
